services:
    data_collector.dwoo:
        class: Dwoo\SymfonyBundle\DataCollector\DwooDataCollector
        public: false
        tags:
            - { name: data_collector, template: "@Dwoo/Collector/dwoo.html.twig", id: "dwoo" }
