services:
    data_collector.dwoo:
        class: Dwoo\SymfonyBundle\DataCollector\DwooDataCollector
        public: false
        tags:
            - { name: data_collector, template: "data_collector/dwoo.html.twig", id: "dwoo.data_collector" }
