services:
  dwoo:
    class: Dwoo\Core
  template.engine.dwoo:
    class: Dwoo\SymfonyBundle\DwooEngine
    tags:
      - { name: templating.engine }
      - { name: monolog.logger, channel: DwooBundle }
    arguments: [@dwoo]
