services:
  dwoo:
      class: Dwoo\Core
  templating.engine.dwoo:
      class: Dwoo\SymfonyBundle\DwooEngine
      tags:
          - { name: templating.engine }
          - { name: monolog.logger, channel: DwooBundle }
      arguments: ["@dwoo", "@service_container", "@templating.name_parser", "@templating.loader", "%dwoo.options%", "@?templating.globals"]
  dwoo.templating.finder:
      class: Dwoo\SymfonyBundle\CacheWarmer\DwooTemplateFinder
      arguments: ["@kernel", "@templating.filename_parser", "%kernel.root_dir%/Resources"]
  dwoo.plugin.asset:
      class: Dwoo\SymfonyBundle\Plugins\Functions\PluginAsset
      public: false
      tags:
          - { name: dwoo.plugin }
      arguments: ["@dwoo", "@assets.packages"]
  dwoo_engine: "@templating.engine.dwoo"
  dwoo.engine: "@templating.engine.dwoo"